### PR TITLE
gtk3 must be built with X

### PR DESCRIPTION
**Pull request by kuzetsa**
fix for bug #611104

Package-Manager: Portage-2.3.3, Repoman-2.3.1

### CODE REVIEW

**Comment by kuzetsa** [comment]
Similar fix is going to be needed for bug #611816

**Comment by mudler** [comment]
Thanks! 
Can you drop the `$Id$` line as per https://bugs.gentoo.org/show_bug.cgi?id=611234 ?

**Comment by kuzetsa** [comment]
Sure, no worries - think I only missed that $Id$ thing because there was movement on 611234 while the gtk3[X] commits were still in the oven :)

**Comment by mudler** [comment]
Merged, thanks! :+1:

**Pull request closed without merging**
